### ISSUE TITLE
problem when trying to format date

### ISSUE THREAD

**Issue by luiz04nl** [Pmovil/CN1WindowsPort#19]
Problem when trying to format date, the following code works perfectly on ios and android but generates failure on CN1WindowsPort:

```
    String dataClassifcado = "2010-10-10";
    Date d = new Date();
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    try {
        d = new Date(format.parse(dataClassifcado).getTime());
    } catch (com.codename1.l10n.ParseException ex) {
        ex.printStackTrace();
    }

    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    long sdf = d.getTime();
    String dataFormatada = dateFormat.format(sdf);]
```

Stack traces aren't supported at the moment
java.lang.RuntimeException: org.xmlvm._nNotYetImplementedException: XMLVM: Not Yet Implemented: Red class access removed: com.ibm.icu.util.TimeZone getTimeZone

   at java.util.SimpleTimeZone_21.run()

   at java.security.AccessController.doPrivileged(PrivilegedAction n1)

   at java.util.SimpleTimeZone.getICUTimeZone(String n1)

   at java.util.SimpleTimeZone.this(Int32 n1, String n2, Int32 n3, Int32 n4, Int32 n5, Int32 n6, Int32 n7, Int32 n8, Int32 n9, Int32 n10, Int32 n11)

   at java.util.SimpleTimeZone.this(Int32 n1, String n2, Int32 n3, Int32 n4, Int32 n5, Int32 n6, Int32 n7, Int32 n8, Int32 n9, Int32 n10)

   at java.util.TimeZones.getTimeZones()

   at java.util.TimeZone.initializeAvailable()

   at java.util.TimeZone.getTimeZone(String n1)

   at com.codename1.l10n.SimpleDateFormat.parse(String n1)

   at userclasses.StateMachine.onMainForm_1BntDatasAction(Component n1, ActionEvent n2)
The thread 0xaec has exited with code 0 (0x0).
The thread 0x114 has exited with code 0 (0x0).

**Comment by luiz04nl** [comment]
is there any other way to make it work, perhaps through native interfaces?

**Comment by FabricioCabeca** [comment]
The problem is that it relies on a class that is not implemented in xmlvm, you can either avoid using it or suggest a fix in  java.util.SimpleTimeZone.getICUTimeZone, as we don't use it it may take a while for us to fix as we are focused on the features we use most.

Did you see com.ibm.icu.util.TimeZone in the original source ? Maybe you just need to include this if it is there.
